name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the project's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java Development Kit (JDK) 21
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Step 4: Build the project using Gradle
      - name: Build the project
        run: ./gradlew build --stacktrace

      # Step 5: Run the project's tests
      - name: Run tests
        run: ./gradlew test

      # (Optional) Step 6: Generate build artifacts for future use (if needed)
      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: build/libs/