name: Java CI with Gradle
on:
  push:
    branches: [main] # Trigger on push to the main branch
  pull_request:
    branches: [main] # Trigger on pull requests to the main branch

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Add Execute Permission to Gradlew Script
        run: chmod +x gradlew

      - name: Build Project Using Gradle
        run: ./gradlew build